# Generated by Django 4.1.7 on 2023-03-13 20:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('TypeId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('PostId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('CreationDate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('PostTitle', models.CharField(max_length=100, unique=True)),
                ('PostPhoto', models.CharField(default=0, max_length=100)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.users')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.types')),
            ],
        ),
    ]
