# Generated by Django 4.1.7 on 2023-03-27 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_posts_postcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PostType', to='Main.types'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PostAuthor', to='Main.users'),
        ),
    ]
